### PR TITLE
Js2

### PR DESCRIPTION
**Pull request by Tactikerl**
Please see readme.txt file for more information.

### CODE REVIEW

**Comment by Gonlonge** [comment]
Looks like I can log in without a user I am not sure if you are aware of that

**Comment by Tactikerl** [comment]
> Looks like I can log in without a user I am not sure if you are aware of that

Could you check local storage in the browser and send me a screencap in discord?

**Comment by Melisa-Zorraindo** [comment]
I had no problems logging in, but the profile link sends me to a hardcoded page, not to my actual profile. Not sure if I'm checking the right branch or if this is something you're still working on. Also, there's a massive horizontal scrollbar on the homepage, I couldn't find what was causing it, sorry. Search functionality works. I could create a post as well, but I couldn't edit or delete my post, I guess because I couldn't access my profile page? let me know if I'm in the wrong branch, please.

**Comment by Anclagen** [comment]
Posting, editing and deleting works fine, I too found the scroll bar but that was caused by a post, so you need to add some word-break to your paragraph elements. Your body element needs class "min-vh-100", to push the footer to the bottom at the moment you have "mh-vh-100", as at the moment your footer doesn't get pushed to the bottom on your post specific page.

**Comment by Jenfer93** [comment]
I like your design a lot, and got logged in directly when signing up, I'm sure that's what your going for, but I aswell had a hard coded profilepage without my user info, and I was able to create a post, that worked perfectly, and I could see one and one post (as a in a single post and not just the list of posts) but I was unable to edit or delete it, but I can see other has managed that, so I'm not sure if I'm on the right place? 😅 But great work!

**Comment by volvojakobsen** [comment]
your search function is case sensitive you should:
document.getElementById("searchInput").value.toLowerCase();

post.title.toLowerCase().includes(searchTerm) ||
post.body.toLowerCase().includes(searchTerm)

this way the search would not be case sensitive and yield more results.

**Review by martink-rsa — COMMENTED** [review]
Hi Karl-Morten,

Good job with this assignment so far. A couple of bugs need to be handled, and then the filter/sort feature needs to be added.

❌User with @noroff.no or @stud.noroff.no email can register profile
✔Registered user can login
✔User can view a post content feed
❌User can filter the post content feed
✔User can search the post content feed
✔User can view a post content item by ID
❌User can create a post content item
❌User can update a post content item
✔User can delete a post content item
 
## Can’t create post:

There seem to be imports missing.

## Can’t edit post:

I am getting the following error:
```
renderPosts.mjs:229          PUT https://nf-api.onrender.com/api/v1/social/posts6558?_author=true 404
```
It might be that there is a slash missing between ‘posts’ and the id?

## No filtering/sorting:

There is no filtering/sorting. I discussed this with you while reviewing so you are aware of what needs to be done.

Please don’t hesitate to contact the tutors if you need assistance.

Kind regards,
Martin

**Comment by martink-rsa** [comment]
Recent fixes leaves the project at the following state:

✔User with @noroff.no or @stud.noroff.no email can register profile
✔Registered user can login
✔User can view a post content feed
❌User can filter the post content feed
✔User can search the post content feed
✔User can view a post content item by ID
✔User can create a post content item
✔User can update a post content item
✔User can delete a post content item

**Pull request merged**
